[book]
authors = ["Vincenzo Palazzo <vincenzopalazzodev@gmail.com>"]
language = "en"
multilingual = false
src = "."
title = "Async Main and Test initiative"

[output.html]
no-section-label=true
git-repository-url="https://github.com/rust-lang/{{GROUP_SLUG}}"
